const languageConstants = {
  en: {
    signIn: "Sign In",
    signUp: "Sign Up",
    newToNetflix: "New to Netflix?",
    signUpNow: "Sign up now.",
    signInNow: "Sign in now.",
    play: "Play",
    moreInfo: "More Info",
    nowPlaying: "Now Playing",
    popular: "Popular",
    topRated: "Top Rated",
    upcoming: "Upcoming",
    search: "Search",
    gptSearchPlaceholder: "what would you like to watch today?",
  },

  tamil: {
    signIn: "உள்நுழைக",
    signUp: "பதிவு செய்க",
    newToNetflix: "Netflix க்கு புதியவரா?",
    signUpNow: "இப்போது பதிவு செய்க.",
    signInNow: "இப்போது உள்நுழைக.",
    play: "இயக்கு",
    moreInfo: "மேலும் தகவல்",
    nowPlaying: "இப்போது இயங்குகிறது",
    popular: "பிரபலமானது",
    topRated: "முதல் தரமதிப்பீடு",
    upcoming: "விரைவில் வரவிருக்கிறது",
    search: "தேடல்",
    gptSearchPlaceholder: "இன்று என்ன பார்க்க விரும்புகிறீர்கள்?",
  },

  hindi: {
    signIn: "साइन इन",
    signUp: "साइन अप",
    newToNetflix: "Netflix में नए हैं?",
    signUpNow: "अब साइन अप करें।.",
    signInNow: "अब साइन इन करें।.",
    play: "चलाएं",
    moreInfo: "अधिक जानकारी",
    nowPlaying: "अब चल रहा है",
    popular: "लोकप्रिय",
    topRated: "शीर्ष रेटेड",
    upcoming: "आगामी",
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
  },

  spanish: {
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    newToNetflix: "¿Nuevo en Netflix?",
    signUpNow: "Regístrate ahora.",
    signInNow: "Inicia sesión ahora.",
    play: "Reproducir",
    moreInfo: "Más información",
    nowPlaying: "Ahora en reproducción",
    popular: "Popular",
    topRated: "Mejor valorados",
    upcoming: "Próximamente",
    search: "Buscar",
    gptSearchPlaceholder: "¿Qué quieres ver hoy?",
  },

  french: {
    signIn: "Se connecter",
    signUp: "S'inscrire",
    newToNetflix: "Nouveau sur Netflix ?",
    signUpNow: "Inscrivez-vous maintenant.",
    signInNow: "Connectez-vous maintenant.",
    play: "Lire",
    moreInfo: "Plus d'infos",
    nowPlaying: "En cours de lecture",
    popular: "Populaire",
    topRated: "Les mieux notés",
    upcoming: "À venir",
    search: "Rechercher",
    gptSearchPlaceholder: "Que voulez-vous regarder aujourd'hui ?",
  },
};

export default languageConstants;
